services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.0.4
    container_name: qbittorrent
    environment:
      - PUID=1000         # Change this to the user ID of the user who will own the files
      - PGID=1000         # Change this to the group ID of the user
      - WEBUI_PORT=8082   # Port for the Web UI
    volumes:
      - ~/mcenter/downloads:/downloads  # Path to store downloaded files
      - ~/mcenter/qbittorrent/config:/config        # Path to store configuration
    ports:
      - 8082:8082       # Expose the Web UI port
      - 6881:6881       # Expose the default BitTorrent port (optional)
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:0.22.1461
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ~/mcenter/jackett/data:/config
      - ~/mcenter/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.19.3
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ~/mcenter/radarr/data:/config
      #- ~/mcenter/media:/movies #optiddonal
      - ~/mcenter/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ~/jellyfin/media:/downloads

  jellyfin:
    image: jellyfin/jellyfin:10.10
    container_name: jellyfin
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - ~/mcenter/jellyfin/config:/config
      - ~/mcenter/jellyfin/cache:/cache
      - ~/mcenter/downloads:/media
    ports:
      - "8096:8096"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ~/mcenter/calibre/data:/config
      # allow upload https://www.reddit.com/r/Calibre/comments/mu3qh1/calibreweb_how_do_i_upload_books/
      - ~/mcenter/calibre/library:/books:z
    ports:
      - 8083:8083
    restart: unless-stopped
